# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wifimon < Formula
  desc "Real-time Wi-Fi terminal monitor with Growl notifications"
  homepage "https://github.com/cumulus13/go-wifimon"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cumulus13/go-wifimon/releases/download/v1.0.5/wifimon_1.0.5_darwin_amd64.tar.gz"
      sha256 "91456082dfe73bd00be3af3f8554bed9fdf19128ed5a642d9fa71c12e2ba381b"

      define_method(:install) do
        bin.install "wifimon"
        (pkgshare/"assets").install Dir["assets/*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cumulus13/go-wifimon/releases/download/v1.0.5/wifimon_1.0.5_darwin_arm64.tar.gz"
      sha256 "092b92c239386d785f4cf2dd898c68c4c9db671676af3f47f8bbe4f549b75f76"

      define_method(:install) do
        bin.install "wifimon"
        (pkgshare/"assets").install Dir["assets/*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cumulus13/go-wifimon/releases/download/v1.0.5/wifimon_1.0.5_linux_amd64.tar.gz"
      sha256 "3c1682a666aa0b88944d07bbf3d931365bfa8c4524bad519d215f617ce8a7e17"
      define_method(:install) do
        bin.install "wifimon"
        (pkgshare/"assets").install Dir["assets/*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cumulus13/go-wifimon/releases/download/v1.0.5/wifimon_1.0.5_linux_arm64.tar.gz"
      sha256 "d5efa95ee11e0013149db26a9e9135a4d531fc69bed4ca4a94f6471af8c4fc3e"
      define_method(:install) do
        bin.install "wifimon"
        (pkgshare/"assets").install Dir["assets/*"]
      end
    end
  end

  test do
    system "#{bin}/wifimon", "--version"
  end
end
